name: Deploy and Notify

on:
  push:
    branches:
      - master

jobs:
  deploy-and-notify:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Wait for GitHub Pages to deploy
        run: |
          # 等待部署完成,最多等待5分钟
          for i in {1..30}; do
            status=$(curl -s -o /dev/null -w "%{http_code}" ${{ github.event.repository.html_url }})
            if [ $status -eq 200 ]; then
              echo "Deployment successful!"
              break
            fi
            echo "Waiting for deployment to complete..."
            sleep 10
          done

      - name: Send Telegram Notification
        if: success()
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: |
          message="GitHub Pages 部署完成! 🎉%0A仓库: ${{ github.repository }}%0A访问地址: ${{ github.event.repository.html_url }}"
          curl -s -X POST https://api.telegram.org/bot${TELEGRAM_BOT_TOKEN}/sendMessage -d chat_id=${TELEGRAM_CHAT_ID} -d text="${message}"